In [1]:
import tensorflow as tf
import numpy as np

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


D:\Winpython\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy=MinMaxScaler(xy)
x_data=xy[:,0:-1]
y_data=xy[:,[-1]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 1])
W = tf.Variable(tf.random_normal([4, 1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch graph
with tf.Session() as sess:
   # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})                               
        if step %200==0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)



0 Cost:  0.17658544 
Prediction:
 [[ 0.7072871 ]
 [ 0.28450885]
 [ 0.12981203]
 [-0.01406959]
 [ 0.09284621]
 [ 0.13780949]
 [-0.30914026]
 [-0.22958982]]
200 Cost:  0.1741651 
Prediction:
 [[ 0.71120995]
 [ 0.28843313]
 [ 0.13309303]
 [-0.01151475]
 [ 0.09585029]
 [ 0.14071873]
 [-0.3071133 ]
 [-0.22756359]]
400 Cost:  0.17178498 
Prediction:
 [[ 0.71509296]
 [ 0.29232097]
 [ 0.13634376]
 [-0.00898297]
 [ 0.0988266 ]
 [ 0.14360149]
 [-0.30510265]
 [-0.22555211]]
600 Cost:  0.1694372 
Prediction:
 [[ 0.71895504]
 [ 0.29618594]
 [ 0.13957506]
 [-0.00646672]
 [ 0.10178524]
 [ 0.14646682]
 [-0.3031055 ]
 [-0.22355524]]
800 Cost:  0.16712841 
Prediction:
 [[ 0.72277755]
 [ 0.30001485]
 [ 0.14277686]
 [-0.00397296]
 [ 0.10471658]
 [ 0.14930601]
 [-0.30112422]
 [-0.22157285]]
1000 Cost:  0.16485119 
Prediction:
 [[ 0.72657925]
 [ 0.30382103]
 [ 0.14595906]
 [-0.00149487]
 [ 0.10763015]
 [ 0.1521279 ]
 [-0.29915655]
 [-0.21960485]]
1200 Cost:  0.1626114 
Prediction:
 [[ 0.7303426 ]
 [ 0.30759